### PR TITLE
Support Blending Modes

### PR DESCRIPTION
**Pull request by mmaciola**
Patch introduces blending options such as Normal, Screen, Multiply, Overlay,
Darken, Lighten, ColorDodge, ColorBurn, HardLight, SoftLight, Difference,
Exclusion

### CODE REVIEW

**Comment by hermet** [comment]
@mmaciola I will check it. That would be better if we made a consensus for the interfaces prior to  implementate bodies.

**Comment by mmaciola** [comment]
Updated commit message, optimized `BLEND_COLORS()` function and fixed for translucent rle

**Comment by projectitis** [comment]
@hermet @mmaciola I would really like blending modes supported :) 

What is required to this work to make it suitable for ThorVG?  I am happy to contribute.

Hermet do you suggest a different interface? Please explain your idea.

**Comment by hermet** [comment]
@projectitis Although I didn't review this yet, I guess this approach is good. I think we can work on this after v0.9 release?

**Comment by hermet** [comment]
replace with this: https://github.com/thorvg/thorvg/pull/1500

**Pull request closed without merging**
