### PR TITLE
loader/webp: Support static webp loader option

### PR DESCRIPTION
**Pull request by JSUYA**
Built to libwebp code in to support the static option of webp loader.
(code from :https://github.com/jacklicn/libwebp)

There are some code fixes related to -Wnarrowing and -fpermissive flags.
(Add type casting code).

issue: https://github.com/thorvg/thorvg/issues/1427

### CODE REVIEW

**Comment by JSUYA** [comment]
Since thorvg only need webp's decode(and *GetInfo) feature, I tried various ways to minimize this, but couldn't find an idea.
If you have a good idea, please share to me.

**Comment by JSUYA** [comment]
We need more code modifications related to type casting in the Windows environment.
and `webp/decode.h` can not found  even if the libwebp library is checked to exist in Windows env. I need to think more about this part.
It might take some time...

**Comment by hermet** [comment]
binary size comparison:

- thorvg+svg+tvg+lottie: 270kb
- static webp: 240kb
- static png: 11kb
- static jpg: 43kb

**Comment by JSUYA** [comment]
> binary size comparison:
> 
> * thorvg+svg+tvg+lottie: 270kb
> * static webp: 240kb
> * static png: 11kb
> * static jpg: 43kb

I tried deleting the encode and SIMD code from static_webp.
https://github.com/JSUYA/thorvg/commit/098390f46cd03f08f5a4bfbe144158d5579b1115
before
```
$ ls -al /usr/local/lib/x86_64-linux-gnu/libthorvg.so.0.11.99 
-rwxr-xr-x 1 root root 524576 Oct 12 16:59 /usr/local/lib/x86_64-linux-gnu/libthorvg.so.0.11.9
```
after
```
$ ls -al /usr/local/lib/x86_64-linux-gnu/libthorvg.so.0.11.99 
-rwxr-xr-x 1 root root 352368 Oct 12 16:51 /usr/local/lib/x86_64-linux-gnu/libthorvg.so.0.11.99
```
I think i could reduce to further since only WebPGetInfo() and WebPDecodeBGRA() are used, but I haven't found a better way.
(I'm worried that other issues related to webp image.)

What binary size of static webp can we allow?

**Comment by hermet** [comment]
just to make it sure:  the dynamic linking is an another topic, out of this contribution.

**Comment by hermet** [comment]
@JSUYA Hello, may I ask you to rebase the patch https://github.com/JSUYA/thorvg/commit/098390f46cd03f08f5a4bfbe144158d5579b1115  ?

**Comment by hermet** [comment]
https://github.com/thorvg/thorvg/pull/1682

**Pull request closed without merging**
