### PR TITLE
API clean up

### PR DESCRIPTION
**Pull request by hermet**
BETA -> Official 0.10
- unique_ptr<Picture> Accessor::set(std::unique_ptr<Picture> picture, std::function<bool(const Paint* paint)> func);
- static Accessor::std::unique_ptr<Accessor> gen();
- Result Shape::order(bool strokeFirst);

Modify:
- SwCanvas::Colorspace::ABGR8888_STRAIGHT -> SwCanvas::Colorspace::ABGR8888S
- SwCanvas::Colorspace::ARGB8888_STRAIGHT -> SwCanvas::Colorspace::ARGB8888S

Removal:
- Result Picture::viewbox(float* x, float* y, float* w, float* h) const;

@Issue: https://github.com/thorvg/thorvg/issues/1372

### CODE REVIEW

**Comment by hermet** [comment]
@mgrudzinska I would appreciate it if you could provide the Shape::order() CAPI binding and test.

**Review by mgrudzinska — COMMENTED** [review]
since we are considering introducing markers, the 'order' api will be deprecated sooner or later. so maybe we should change it before promoting?
like ```order(int fill, int stroke, int markers)``` ?
or don;t promote it?

**Comment by hermet** [comment]
> since we are considering introducing markers, the 'order' api will be deprecated sooner or later. so maybe we should change it

@mgrudzinska I'm not certain about anything. While the feature could potentially be implemented on the SVGloader side (due to it being part of the SVG spec, not others), I currently have no plans to undertake the task of adding this feature myself. This means that markers will not be introduced unless someone intentionally attempts to do so. Instead we keep the API in beta, we might consider making it official now and then deprecating it in a future 2.0 release.

That's my opinion and I would like to accept your choice since that api was introduced by you. If you like to keep it under beta. then it's ok. but no marker parameters now.

**Comment by mgrudzinska** [comment]
@hermet, let's do it your way. let's promote order api, since as you wrote, we are not sure whether and when markers will be introduced

**Review by mgrudzinska — APPROVED** [review]

**Pull request merged**
