### PR TITLE
release: bump up version v0.11

### PR DESCRIPTION
**Pull request by hermet**
https://github.com/thorvg/thorvg/issues/1669

**Performance Test, within the margin of error:**
v0.10: rendering = 0.015295s,  average = 0.015833s
v0.11: rendering = 0.015845s,  average = 0.015880s

**Binary Comparison (vs 0.10):**
Full feature (static) = 280kb -> 339kb
Full feature (dynamic) = 217kb -> 276kb
SVG Only = 198kb -> 196kb
Lottie Only = 179kb -> 194kb

**ThorVG Viewer Update:** 
https://github.com/thorvg/thorvg.viewer/pull/6

### CODE REVIEW

**Comment by hermet** [comment]
@capnm Helo, Thorvg v0.11 is just around the corner. I would appreciate it if you could verify it with the Godot using this branch. Thanks.

**Comment by capnm** [comment]
@hermet Sure, I'll take a look at it tonight.
Could you this time make a `hermet/release` → 0.11.x release branch in Github alongside to the main branch?
I think it would then be easier to track the changes to the current main branch.

**Comment by hermet** [comment]
> @hermet Sure, I'll take a look at it tonight. Could you this time make a `hermet/release` → 0.11.x release branch in Github alongside to the main branch? I think it would then be easier to track the changes to the current main branch.

Ok, I will thanks.

**Comment by hermet** [comment]
ThorVG Viewer Update: https://github.com/thorvg/thorvg.viewer/pull/6

**Comment by hermet** [comment]
@capnm ==> https://github.com/thorvg/thorvg/pull/1680

**Pull request closed without merging**
