### PR TITLE
sw_engine: ++skip radial gradient filling.

### PR DESCRIPTION
**Pull request by hermet**
Do not rendering if the filling has an invalid condition.

### CODE REVIEW

**Review by mgrudzinska — CHANGES_REQUESTED** [review]
`fill->incvalid` is a bool, so no need. to use tvg::zero
but the problem is, that according to svg std r<0 is an error, but r==0 is ok. introducing this change we can not fulfill svg std
and I don;t think this affects performance much, these are very rare cases when r==0

**Comment by hermet** [comment]
> `fill->incvalid` is a bool, so no need. to use tvg::zero but the problem is, that according to svg std r<0 is an error, but r==0 is ok. introducing this change we can not fulfill svg std and I don;t think this affects performance much, these are very rare cases when r==0

@mgrudzinska This doesn't hurt the svg spec. thorvg doesn't do for radial when radius is zero. Still r == 0 is acceptable by thorvg and radius can be an animator factor thus it needs.

**Comment by mgrudzinska** [comment]
> @mgrudzinska This doesn't hurt the svg spec. Regardless of this change, thorvg doesn't do for radial when radius is zero. Still r == 0 is acceptable by thorvg and radius can be an animation factor thus it needs.

before your change the sample below was rendered, so this change affects svg specs
```
<svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <radialGradient id="myGradient" cx="1" cy="0" r="0">
      <stop offset="0" stop-color="gold" />
      <stop offset="1" stop-color="red" />
    </radialGradient>
  </defs>

  <rect x="0" y="0" width="7" height="7" fill="url(#myGradient)" />
</svg>
```

but if you don't agree and still want to push this pr, then you should handle rle as well, not only rectangles

**Comment by hermet** [comment]
> but if you don't agree and still want to push this pr, then you should handle rle as well, not only rectangles

Got it, my fault. Let's come up with the logic.

**Pull request closed without merging**
