### PR TITLE
++ pkg enhancement

### PR DESCRIPTION
**Pull request by hermet**

### CODE REVIEW

**Comment by vtorri** [comment]
@hermet you set the variable `stripping` to `true` by default, then if b_sanitize is != none, set it to `true`

in the target:

strip: stripping,

to have something similar to what you had

**Comment by vtorri** [comment]
if you force stripping with this:

```
@@ -53,6 +53,7 @@ thorvg_lib = library(
     dependencies           : thorvg_lib_dep,
     install                : true,
     cpp_args               : compiler_flags,
+    strip                  : true,
     gnu_symbol_visibility  : 'hidden',
     override_options       : override_options
 )
```

if **you install** the lib (strip is done on install rule), are the symbols stripped ?

**Comment by hermet** [comment]
> if **you install** the lib (strip is done on install rule), are the symbols stripped ?

Ah, I see. I checked the result in the build folder, but the stripping process is actually performed during the installation.

**Comment by capnm** [comment]
Clang moved the stripping part from compiler to the linker ...
https://stackoverflow.com/questions/6085491/gcc-vs-clang-symbol-stripping

**Comment by hermet** [comment]
> if you force stripping with this:
> 
> ```
> @@ -53,6 +53,7 @@ thorvg_lib = library(
>      dependencies           : thorvg_lib_dep,
>      install                : true,
>      cpp_args               : compiler_flags,
> +    strip                  : true,
>      gnu_symbol_visibility  : 'hidden',
>      override_options       : override_options
>  )
> ```
> 
> if **you install** the lib (strip is done on install rule), are the symbols stripped ?

So as far as I tested, strip works in default. when I turn it off with meson option, it doesn't invovled. so looks fine.

**Comment by capnm** [comment]
Can confirm, meson does it in the install part:
```
[41/42] meson install --no-rebuild
Installing src/libthorvg.so.0.9.99 to thorvg_64/lib/x86_64-linux-gnu
...
Stripping target 'src/libthorvg.so.0.9.99'.
...
1.592.864 svg2png_build/src/libthorvg.so.0.9.99
  200.672 thorvg_64/lib/x86_64-linux-gnu/libthorvg.so.0.9.99
```

**Comment by vtorri** [comment]
i would do the contrary:
 1. by default, the option is debugoptimized, so you shouln't strip by default. So in the project() function : `strip : false`
 2. in src/meson.build, before the b_sanitize test:

```
stripping = get_option('strip')
```

 3. in src/meson.build, in the b_sanitize test:

```
stripping = true
```

 4. below, in the library() call (around line 54), add:

```
strip: stripping,
```

**Comment by hermet** [comment]
> 5\. in src/meson.build, in the b_sanitize test:
> 
> 
> ```
> stripping = true
> ```

@vtorri Thanks for comments. 2 things.
1. Sanitize test needs to strip? Just wonder why.
2. We'd rather to keep the strip in default for someone who has no idea about it at all. Even though it's enabled, no troubles in debugging most cases. I expect people could disable the strip option when it's necessary.

**Review by vtorri — APPROVED** [review]

**Review by capnm — APPROVED** [review]

**Pull request merged**
