### PR TITLE
Try to get the GL backend working

### PR DESCRIPTION
**Pull request by RuiwenTang**
This is an other draft which I am trying to rewrite exists GL backend code and make it work as expected.

Changes under examples directory can be ignored. I change to use SDL2 because I can not create a OpenGL context with EFL on my macbook. The clang-format and some code format changes can also be ignored.

Because I want to use some common feature in modern Open GL/GLES, like vertex array object, uniform buffer object, so I changed all existing buffer and shader creation code. Also I thought no matter what GPU backend we choose in the future, they all need to convert polygons to triangles. So I put the tessellation algorithm outside the gl_engine directory.

Current state:

- [x]  Fill Path
- [x] Stroke Path
- [x] Dash Effect In Stroke
- [x]  Clip Path
- [x] Linear Gradient
- [x]  Radial Gradient
- [x]  Image
- [ ]  Blending
- [x]  Masking
- [ ]  Contour AA

### CODE REVIEW

**Comment by RuiwenTang** [comment]
Current rendering result:

### src/example/Path
#### wireframe

Screenshot from 2023-07-23 19-02-04

#### color
Screenshot from 2023-07-23 19-03-36

### src/example/Stroke
#### wireframe
Screenshot from 2023-07-23 19-02-49
#### color
Screenshot from 2023-07-23 19-03-19

**Comment by vtorri** [comment]
have you tried to use evas gl ?

**Comment by RuiwenTang** [comment]
> have you tried to use evas gl ?

I just run the example code in my macbook. 
The `elm_glview_add` function returned null.
And none of callback function set by `elm_glview_init_func_set` or `elm_glview_render_func_set` get called.
Also get the following error message in the console.
image

**Comment by vtorri** [comment]
maybe a problem with the opengl support on mac

**Comment by RuiwenTang** [comment]
## src/examples/RadialGradient
radial_gradient
## src/examples/ClipPath
clip_path
## src/examples/SceneClipper
scene_clipper

**Comment by vtorri** [comment]
@RuiwenTang have you tried to benchmark the GL path vs the software one ?

**Comment by vtorri** [comment]
@RuiwenTang ho btw: http://www.enlightenment.org/develop/legacy/tutorial/gl_2d_tutorial

**Comment by RuiwenTang** [comment]
> @RuiwenTang have you tried to benchmark the GL path vs the software one ?

No, the gl engine is still a work in progress and not all rendering features have been implemented.
I need to make every things work, then consider how to make them faster.
But I don't think GL backend is slower than CPU raster :)

**Comment by RuiwenTang** [comment]
## src/examples/Masking
masking
## src/examples/MaskingMethods
masking_method

**Comment by RuiwenTang** [comment]
## src/examples/StrokeLine
Screenshot from 2023-08-05 17-30-26

**Comment by hermet** [comment]
@RuiwenTang hello, on clearing PR, is this still necessary?

**Comment by RuiwenTang** [comment]
> @RuiwenTang hello, on clearing PR, is this still necessary?

No, it can be closed :)

**Pull request closed without merging**
