### PR TITLE
clipper refactoring

### PR DESCRIPTION
**Pull request by hermet**
Keep small size & neat apis.

The main focus is to reduce the paint size and remove an api at the out of user demand.

### CODE REVIEW

**Comment by hermet** [comment]
@mgrudzinska could you please verify this?

**Comment by mgrudzinska** [comment]
@hermet, sorry for late replay. I'll take a look today

**Comment by hermet** [comment]
@mgrudzinska please don't be pushed yourself. i don't think this is a serious patch.

**Comment by mgrudzinska** [comment]
@hermet kinda late, but I've read the code and checked, works fine

**Pull request merged**
