### PR TITLE
fix usage of TVG_API

### PR DESCRIPTION
**Pull request by vtorri**
infa: fix usage of TVG_API
details

@issue: https://github.com/thorvg/thorvg/issues/1446

### CODE REVIEW

**Comment by vtorri** [comment]
i have tested with 3 configurations (shared, static and both) with these 3 scripts:

```
#! /bin/bash

export PATH=/opt/efl_64/bin:$HOME/ewpi_64/bin:$PATH
export PKG_CONFIG_PATH=/opt/efl_64/lib/pkgconfig:$HOME/ewpi_64/lib/pkgconfig
export CPPFLAGS="-I/opt/ewpi_64/include -DECORE_WIN32_WIP_POZEFLKSD"
export CFLAGS="-g3 -ggdb3 -Og -pipe"
export CXXFLAGS="-g3 -ggdb3 -Og -pipe"
export LDFLAGS=-L$HOME/ewpi_64/lib

rm -rf builddir_shared

meson setup \
      --prefix=/opt/thorvg_64 \
      --buildtype=debug \
      --default-library shared \
      -Dloaders=all \
      -Dsavers=all \
      -Dbindings=capi \
      -Dtools=all \
      -Dexamples=true \
      -Dtests=true \
      builddir_shared

ninja -j8 -C builddir_shared install
```

```
#! /bin/bash

export PATH=/opt/efl_64/bin:$HOME/ewpi_64/bin:$PATH
export PKG_CONFIG_PATH=/opt/efl_64/lib/pkgconfig:$HOME/ewpi_64/lib/pkgconfig
export CPPFLAGS="-I/opt/ewpi_64/include -DECORE_WIN32_WIP_POZEFLKSD"
export CFLAGS="-g3 -ggdb3 -Og -pipe"
export CXXFLAGS="-g3 -ggdb3 -Og -pipe"
export LDFLAGS=-L$HOME/ewpi_64/lib

rm -rf builddir_static

meson setup \
      --prefix=/opt/thorvg_64 \
      --buildtype=debug \
      --default-library static \
      -Dloaders=all \
      -Dsavers=all \
      -Dbindings=capi \
      -Dtools=all \
      -Dexamples=true \
      -Dtests=true \
      builddir_static

ninja -j8 -C builddir_static install
```

```
#! /bin/bash

export PATH=/opt/efl_64/bin:$HOME/ewpi_64/bin:$PATH
export PKG_CONFIG_PATH=/opt/efl_64/lib/pkgconfig:$HOME/ewpi_64/lib/pkgconfig
export CPPFLAGS="-I/opt/ewpi_64/include -DECORE_WIN32_WIP_POZEFLKSD"
export CFLAGS="-g3 -ggdb3 -Og -pipe"
export CXXFLAGS="-g3 -ggdb3 -Og -pipe"
export LDFLAGS=-L$HOME/ewpi_64/lib

rm -rf builddir_both

meson setup \
      --prefix=/opt/thorvg_64 \
      --buildtype=debug \
      --default-library both \
      -Dloaders=all \
      -Dsavers=all \
      -Dbindings=capi \
      -Dtools=all \
      -Dexamples=true \
      -Dtests=true \
      builddir_both

ninja -j8 -C builddir_both install
```

**Comment by hermet** [comment]
@vtorri  Thanks, here is commit msg format that throvg preferred:
https://github.com/thorvg/thorvg/blob/master/CONTRIBUTING.md

```
infa: fix usage of TVG_API
details

@issue: https://github.com/thorvg/thorvg/issues/1446
```

**Comment by vtorri** [comment]
@hermet done, i think

**Comment by vtorri** [comment]
@hermet should the .pc files also updated with Cflags.private ? it's for static builds with pkgconf (see https://github.com/pkgconf/pkgconf/blob/master/man/pc.5#L99)

**Comment by hermet** [comment]
> @hermet done, i think



> @hermet done, i think

Thanks but I was talking about commit msg. not PR...^^;

You can update the git commit msg using 

"git commit . --amend" 
then 
"git push origin/vtorri_build --force"

**Comment by vtorri** [comment]
@hermet it does not work, and i'm fed up with git.

honestly, i don't care to be the author. Take the patch and commit yourself. Commit message could be:

```
portability: fix usage of TVG_API

Rule of thumb on Windows:
  * for a DLL:
    * if the library is built, set TVG_API to __declspec(dllexport)
    * if the library is used, set TVG_API to __declspec(dllimport)
  * for a static library, set TVG_API to nothing

To set TVG_API for a static library, TVG_STATIC is defined when the stataic library is built.
Otherwise, TVG_API is correctly set for a DLL.
Also sun and intel compilers are handled

@issue: https://github.com/thorvg/thorvg/issues/1446
```

**Comment by hermet** [comment]
> @hermet it does not work, and i'm fed up with git.
> 
> honestly, i don't care to be the author. Take the patch and commit yourself. Commit message could be:
> 
> ```
> portability: fix usage of TVG_API
> 
> Rule of thumb on Windows:
>   * for a DLL:
>     * if the library is built, set TVG_API to __declspec(dllexport)
>     * if the library is used, set TVG_API to __declspec(dllimport)
>   * for a static library, set TVG_API to nothing
> 
> To set TVG_API for a static library, TVG_STATIC is defined when the stataic library is built.
> Otherwise, TVG_API is correctly set for a DLL.
> Also sun and intel compilers are handled
> 
> @issue: https://github.com/thorvg/thorvg/issues/1446
> ```

@vtorri Got it, thanks for helping this.

**Comment by hermet** [comment]
@vtorri  https://github.com/thorvg/thorvg/pull/1449
jfyi, Next time, you can branch out for your change from the main thorvg repo. then I can update it in the same PR.

**Pull request closed without merging**
