### PR TITLE
Change C-style code to C++ code style

### PR DESCRIPTION
**Pull request by rinechran**
Change C-style code to C++ code style

### CODE REVIEW

**Comment by hermet** [comment]
Unless any practical benefits, I think there is no point to change the coding style.

probably, except this:
image

**Comment by rinechran** [comment]
yes The code style remains the same, but the reason for changing a few cases came out as an error in the mscv static integration stone, so I changed it.

**Comment by hermet** [comment]
> yes The code style remains the same, but the reason for changing a few cases came out as an error in the mscv static integration stone, so I changed it.

Could you please share the error message?

**Comment by rinechran** [comment]
Here's a log message.

image
image

ref : https://learn.microsoft.com/en-us/cpp/code-quality/c26440?view=msvc-170&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(C26440)%26rd%3Dtrue
ref : https://msdn.microsoft.com/query/dev17.query?appId=Dev17IDEF1&l=EN-US&k=k(C26493)&rd=true

**Comment by rinechran** [comment]
@hermet  I fully empathize with your opinion and believe it's appropriate to close the issue at hand. Thank you as always for sharing your thoughts

**Pull request closed without merging**
