### PR TITLE
lottie: fixed a compiler warning:

### PR DESCRIPTION
**Pull request by hermet**
error: storing the address of local variable 'context' in '*this.LottieParser::context' [-Werror=dangling-pointer=]
 1255 |     this->context = &context;

issue: https://github.com/thorvg/thorvg/issues/2051

### CODE REVIEW

**Comment by hermet** [comment]
@qarmin Hello. The svg-regression test server recently experienced a breakdown. Could you please take a moment to review it? Thank you.

**Comment by qarmin** [comment]
I was supposed to check what has changed in Thorvg a long time ago, but I couldn't find the time for it - I'll try to check the fuzzer and add appropriate images for the tests this week.

This issue seems to be more of a GitHub problem because the resource is still available and can be manually downloaded, so probably restarting CI will fix problem.

**Comment by hermet** [comment]
@qarmin thanks, since on this topic, if we have additional SVG resources that we want to add to the tests, how can we contribute them in the official package?

**Comment by kisvegabor** [comment]
Sorry, I'm late, but I confirm that this PR solves the issue.

**Pull request merged**
