### PR TITLE
examples/svg: Add target(-t) option.

### PR DESCRIPTION
**Pull request by JSUYA**
Add -t option to the argument of svg example.
-t can specify a svg file located within the example's resource.
You can use this when you want to check the output of just one SVG file.

ex)
$)./build/src/examples/Svg -t cartman.svg

### CODE REVIEW

**Comment by JSUYA** [comment]
No longer need to clean svg files in resource dir and modify NUM_PER_ROW/COL to check for issues.

**Comment by hermet** [comment]
What do you think if we introduce PicturrSVG like PictureTVG. I don't really like to make examples functional.

**Comment by JSUYA** [comment]
> What do you think if we introduce PicturrSVG like PictureTVG. I don't really like to make examples functional.

https://github.com/JSUYA/thorvg/commit/6338bf686765d0a9a036449e4a451d4952659e55
I made an example that draws one simple SVG(logo.svg).
I think that if we add various functions (transformation test, opacity etc.) like PicturePng to this example, inconveniences will still remain.
I still think this PR is a simple feature for contributors.

Is it okay if I add a PictureSvg that outputs 1 SVG?

**Comment by hermet** [comment]
The functionality I mentioned is not actually a separate feature you mentioned(transform, opacity etc); those functions are included under the ThorVG showcases. What I was referring to as 'functional' are actually the command-line functions. These are not about thorvg and user don't need to be digressed by it. I think we can add PictureSVG as like other PictureXXX families.

**Comment by JSUYA** [comment]
I made new PR. https://github.com/thorvg/thorvg/pull/1962

**Pull request closed without merging**
