### PR TITLE
gl_engine: optimize off-screen rendering

### PR DESCRIPTION
**Pull request by RuiwenTang**
This PR optimize the rendering performance by prevent doing full-screen RenderPass resolve:

Because performing a full-screen RenderPass resolve is too expensive.
And most composite cases only require a small area to be rendered off-screen. To improve performance, use the bounds of the Geometry for off-screen rendering whenever possible.

------
With this patch, the **Lottie** example in my computer with release buildtype:

| before | after |
|---------|-----------|
| 截屏2024-07-01 19 39 33   | 截屏2024-07-01 19 40 19        |

And the **Performance** example is faster than CPU raster
截屏2024-07-01 19 43 39

### CODE REVIEW

**Comment by hermet** [comment]
@RuiwenTang Hmm... tested on my side. I couldn't see any performance enhancement.

**Comment by RuiwenTang** [comment]
> @RuiwenTang Hmm... tested on my side. I couldn't see any performance enhancement.

Windows or Linux ? And using release build by append `--buildtype=release` to meson ?

**Review by hermet — APPROVED** [review]
@mgrudzinska Hello, could you please confirm the performance enhancement mentioned above your side?

**Comment by hermet** [comment]
> Windows or Linux ? And using release build by append `--buildtype=release` to meson ?

@RuiwenTang Linux, yes with release.

**Comment by RuiwenTang** [comment]
> > Windows or Linux ? And using release build by append `--buildtype=release` to meson ?
> 
> @RuiwenTang Linux, yes with release. (Although I don't think the release affects this optimization.)

I test the performance on my MacBook. My Ubuntu environment is broken , so will take some time to test the issue on Linux.
 
there are som STL container usage inside gl_engine, so change to use release build can reduce some STL debug code.

**Comment by hermet** [comment]
@RuiwenTang Neither can I see any improvement on my MacBook.
before:
image
after:
image

Note that: Lottie is crashed on my MacBook. (Linux is ok)

**Comment by RuiwenTang** [comment]
@hermet Is your MacBook powered by an ARM chip(M1, M2, M3)?

**Comment by hermet** [comment]
> @hermet Is your MacBook powered by an ARM chip(M1, M2, M3)?

@RuiwenTang ARM M3

**Comment by RuiwenTang** [comment]
> > @hermet Is your MacBook powered by an ARM chip(M1, M2, M3)?
> 
> @RuiwenTang ARM M3

That is much more powerful than mine, which is i7 cpu :(
The current case may not reach the performance bottleneck for your computer.

**Comment by hermet** [comment]
> > > @hermet Is your MacBook powered by an ARM chip(M1, M2, M3)?
> > 
> > 
> > @RuiwenTang ARM M3
> 
> That is much more powerful than mine, which is i7 cpu :( The current case may not reach the performance bottleneck for your computer.

just checked it again. M3 -> M2 :)
but linux pc is much slower than this. it takes more than 100ms on Lottie but no improvement.

**Comment by vtorri** [comment]
just fyi, i've used glew to have opengl on Windows.

* Lottie.exe gl: the window appears with the icons briefly and then the window is black
* Performance gl: the tiger is flickering

**Pull request merged**
