### PR TITLE
wg_engine: multisampling support part 2

### PR DESCRIPTION
**Pull request by SergeyLebedkin**
Full multisampling support including custom blend and compositions.

Must be verified on web and 4K resolution for performance issues

before/after
Blend
BlendMS
before/after
Threads
ThreadsMS

### CODE REVIEW

**Comment by tinyjin** [comment]
@SergeyLebedkin 
**[Before]**
CleanShot 2024-10-18 at 11 46 53

**[After]**
CleanShot 2024-10-18 at 11 49 11

**Comment by SergeyLebedkin** [comment]
In browser environment:

After/Before
image

**Comment by SergeyLebedkin** [comment]
@tinyjin 
Can you plese, also, share your performance tests?

**Comment by tinyjin** [comment]
@SergeyLebedkin Hello I checked again the quality and performance.

In the animation quality perspective, I don't see big changes between main and this. (I also tested without DPR, looked same)

Performance side, `threads.json` animation showed consistent result(FPS, Memory Usage), however `frog_vr` with this patch has difference on FPS.

**[Before]**

120FPS, 35MB

CleanShot 2024-10-22 at 17 33 27@2x

**[After]**

44-50FPS, 36MB

CleanShot 2024-10-22 at 17 36 58@2x

**Comment by SergeyLebedkin** [comment]
@tinyjin 

Are you sure that screenshots are correct? I thing they are swaped.

[After] 44-50FPS, 36MB - must be with MSAA
[Before] 120FPS, 35MB - must be without MSAA

Quality in "After" is much better that on screenshot "Before"

But in any case, we can see peformance drop with MSAA.

**Pull request closed without merging**
