### PR TITLE
infra: specify TVG_API for both static/dynamic linking.

### PR DESCRIPTION
**Pull request by hermet**
Issue: https://github.com/thorvg/thorvg/issues/1234

### CODE REVIEW

**Comment by capnm** [comment]
@hermet 
> issue: #1234 when TVG_BUILD is not set, and no static lib is created, TVG_EXPORT should be set to __declspec(dllimport)

This change caused now Windows issues by Godot's _external_ static linking, i.e. the __declspec(dllimport). Here the code must be now changed directly :thinking: 
-#define TVG_API __declspec(dllimport)
+#define TVG_API

https://github.com/godotengine/godot/pull/76960#issuecomment-1544491279 ...
https://github.com/godotengine/godot/actions/runs/4951907523

**Comment by vtorri** [comment]
the rule is:
* if thorvg lib is built as a shared lib:
  * if the lib is built: TVG_API must be set to __declspec(dllexport)
  * if the lib is used: TVG_API must be set to __declspec(impexport)
 * otherwise (thorvg built as a static lib), TVG_API must be set to nothing

so at some point, you should have a TVG_STATIC set when static lib is requested (and not set for shared lib)

**Comment by vtorri** [comment]
this patch is wrong for binaries. TVG_BUILD must NOT be set for binaries, ONLY for the lib

**Comment by hermet** [comment]
@capnm @vtorri thanks for noti.
Issue created: https://github.com/thorvg/thorvg/issues/1446
will visit it before the next minor update.

**Comment by vtorri** [comment]
@capnm try to patch git repo with #1448 and report in that patch if it fixes your problem

**Pull request merged**
