### PR TITLE
sw_engine: Fix wrong return

### PR DESCRIPTION
**Pull request by JSUYA**
Checking for values smaller than FLT_EPSILON should return false.

### CODE REVIEW

**Comment by hermet** [comment]
@JSUYA hello, any issue of this?

**Comment by JSUYA** [comment]
Sorry for not enough explanation.
This PR is related to https://github.com/thorvg/thorvg/issues/1836. But it doesn't solve it.

`fill->linear.len` value of the gradient is determined and there are several if checks to check this.
If false was being returned normally here, we would have found sooner than the rasterizer step that `len` value is less than 
And as a result, because the renderer does not draw related shapes, I expected that this would be `more strict check` as shapes in unsupported ranges would not be drawn.

I checked SVG example and didn't find any issues.
(In fact, it will be very difficult to find....)


+
As I was writing this comment..  I think it could also seem like another bug.
If you think this is not appropriate, I'll close it. Thank you for your review.

**Review by SergeyLebedkin — APPROVED** [review]

**Comment by hermet** [comment]
Let's keep this for now. We need an obvisus a bug fix by this.

**Comment by JSUYA** [comment]
> Let's keep this for now. We need an obvisus a bug fix by this.

There are some advantages, but the problems associated with that bug will likely persist unless we change the float type to a double type. (I'm not sure if there's a better way for fix.)

**Comment by hermet** [comment]
@JSUYA I want to make it sure this would not occur any side effects. So unless any obivous advantage, I'm hesitage to correct the code. Please let me know If those advantages are obvious.

**Comment by JSUYA** [comment]
> @JSUYA I want to make it sure this would not occur any side effects. So unless any obivous advantage, I'm hesitage to correct the code. Please let me know If those advantages you have.

@hermet Oh I meant float type's advantage. (memory & performance).

**Comment by hermet** [comment]
> > @JSUYA I want to make it sure this would not occur any side effects. So unless any obivous advantage, I'm hesitage to correct the code. Please let me know If those advantages you have.
> 
> @hermet Oh I meant float type's advantage. Could converting to SwCoord be a solution?

No, it wouldn't. let me see it...

**Comment by hermet** [comment]
This appears to be intentional code for distinguishing between drawing and filling operations. Unfilled shapes might be used for composition purposes.

**Pull request closed without merging**
