### PR TITLE
tools svg2tvg: ++Windows port

### PR DESCRIPTION
**Pull request by hermet**
Complete the Windows port build that is currently missing.

@Issue: https://github.com/thorvg/thorvg/issues/882

### CODE REVIEW

**Comment by hermet** [comment]
@vtorri main implementation is come from
`Author: Vincent Torri <vtorri@outlook.fr>  2022-08-20 17:55:16
Committer: Hermet Park <hermetpark@gmail.com>  2022-08-23 22:41:28
Parent: de87cdc71726a89d3ba0e4a6355b2fd97b9c704f (Windows: use _fullpath() instead of fullpath().)
Child:  a863f29512ed78805db896bdae6866d955630ee9 ([svg2png] size limitation while converting the file)
Branches: hermet/tools, master, remotes/origin/dev/tag, remotes/origin/hermet/infra, remotes/origin/hermet/sceneclip, remotes/origin/hermet/tools, remotes/origin/master
Follows: v0.5.0
Precedes: 

    fix compilation of svg2png on Windows`

**Review by vtorri — COMMENTED** [review]
no newline at end of file

**Comment by hermet** [comment]
> no newline at end of file

does it matter?

**Comment by vtorri** [comment]
i like these new lines 
:-)

**Comment by vtorri** [comment]
it compiles, i don't know how to test it

**Review by mgrudzinska — COMMENTED** [review]
works on mac and windows (mingw)

**Pull request merged**
