### PR TITLE
loader/svg: Check whether href id of use is parent or not

### PR DESCRIPTION
**Pull request by JSUYA**
When finding the 'nodeFrom' referenced by `<use>`,
if it is the parent, it is not referenced.

https://www.w3.org/TR/SVG2/struct.html#UseElement
Specification:
If the referenced element is a (shadow-including) ancestor of the ‘use’ element,
then this is an invalid circular reference and the ‘use’ element is in error.

related issue: https://github.com/thorvg/thorvg/issues/2078 SVG_FILE_65171.svg
SVG_FILE_65172.svg

### CODE REVIEW

**Comment by hermet** [comment]
_findNodeById() is used elsewhere (_updateComposite()). You might wanna check for any introduced circular dependency inside _findNodeById() to ensure it addresses any potential issues in one place. Also, we could probably log a message in the error scenario to notify the user that the SVG is invalid data.

**Comment by hermet** [comment]
Perhaps, using a bit-flag or a boolean could be a better option to prevent unnecessary traversing just for error-checking validation. See: https://github.com/thorvg/thorvg/issues/494

**Comment by JSUYA** [comment]
> _findNodeById() is used elsewhere (_updateComposite()). You might wanna check for any introduced circular dependency inside _findNodeById() to ensure it addresses any potential issues in one place. Also, we could probably log a message in the error scenario to notify the user that the SVG is invalid data.

I think this case is different from finding circular references. The purpose of the `<use>` spec is to determine whether something is a parent or not before making a circular reference. Also, `Infinite recursive call` is checked through `depth` check of _cloneNode(). findNodeById() takes a long time as it searches top down. It is not suitable for finding and checking parent. If I modify findNodeById() for that, it will have a big impact on other functions.

**Comment by hermet** [comment]
Ok, rather than "circular dependency", I actually meat to _findParentById()" this one. basically, idea is not different.

**Review by hermet — APPROVED** [review]

**Pull request merged**
